---

- stat: path={{ frontend }}/package.json
  register: project

- name: Ensure node_modules bind point exists in shared folder.
  file: "path={{ frontend }}/node_modules state=directory"

- name: Mount node_modules from VM onto shared folder.
  shell: mount --bind {{ frontend_packages }} {{ frontend }}/node_modules
  become: yes
  become_method: sudo

- name: A package.json will exist on the client.
  shell: npm init -y
  when: project.stat.exists is not defined or project.stat.exists == False
  args:
    chdir: "{{ frontend }}"
    creates: package.json

- name: NPM dependencies will be installed.
  shell: npm install
  args:
    chdir: "{{ frontend }}"