---

- hosts: all
  remote_user: vagrant

  vars_files:
    - settings.yml

  roles:

    - apache-server
    - postgresql-database
    - python3.6
    - django-framework
    - psycopg2-database-adapter
    - npm-packagemanager
    - django-project
    - npm-frontend

  post_tasks:

    - name: Provisioning has completed!
      shell: "true"
      notify:
        - Restart Web Server
        - Restart Database Server
