---

- hosts: all
  remote_user: vagrant

  vars_files:
    - settings.yml

  roles:

    - apache-server
    - django-framework
    - npm-packagemanager
    - django-app
    - npm-frontend

  post_tasks:

    - name: Provisioning has completed!
      shell: "true"
      notify:
        - Restart Server